name: Vercel Production Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: |
          deployment_url=$(vercel --token=${{ secrets.VERCEL_TOKEN }} | grep -o 'https://[a-zA-Z0-9-]*\.vercel\.app')
          echo "VERCEL_BASE_URL=$deployment_url" >> .env
      - name: Inject secrets into .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Install project dependencies
        run: pnpm install
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
